import { SchoolConfig, NewsArticle } from '../types';
import { DEFAULT_THEME_CONFIG } from './themePresets';
import { DEFAULT_APPS_SCRIPT_WEB_APP_URL, DEFAULT_APPS_SCRIPT_FOLDER_ID } from './googleAppsScript';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: '',
  identity: {
    name: '',
    shortName: '',
    tagline: '',
    npsn: '',
    akreditasi: '',
    logoUrl: 'https://i.ibb.co.com/d44hK88L/logo-smpn-1-bengkalis-kecil.png',
    faviconUrl: 'https://i.ibb.co.com/d44hK88L/logo-smpn-1-bengkalis-kecil.png',
    tickerEnabled: false,
    tickerText: '',
    accreditationTickerEnabled: false,
    accreditationTickerText: '',
    accreditationTickerSpeed: 'normal',
    primaryColor: 'blue',
  },
  importantAnnouncement: {
    enabled: false,
    badge: 'PENGUMUMAN',
    text: '',
    theme: 'info',
    speed: 'normal',
    buttonEnabled: false,
    buttonText: '',
    buttonUrl: '',
    isMarquee: true,
    isSticky: true,
  },
  header: {
    heroTitle: '',
    heroSubtitle: '',
    heroImageUrl: '',
    heroCtaText: '',
    heroCtaLink: '',
    secondaryCtaText: '',
    secondaryCtaLink: '',
    highlights: [],
  },
  navMenus: [],
  layoutSections: {
    showHero: true,
    showQuickStats: false,
    showAccreditation: false,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: false,
    showFacilities: false,
    showExtracurriculars: false,
    showVideoEmbed: false,
    showMapEmbed: false,
    showPublicComments: true,
    showVisiMisi: true,
    showGTK: true,
  },
  mobileBottomNav: {
    enabled: true,
    showHome: true,
    showNews: true,
    showAchievements: false,
    showExtracurriculars: false,
    showContact: true,
    styleVariant: 'floating-dock',
    themeColor: 'dark-slate',
    accentColor: 'blue',
    showLabels: false,
    elevatedCenterButton: true,
    showActiveIndicator: true,
  },
  principal: {
    name: '',
    title: '',
    nip: '',
    imageUrl: '',
    quote: '',
    fullSpeech: '',
  },
  ppdb: {
    enabled: false,
    buttonLabel: '',
    buttonLink: '',
    openInNewTab: false,
    academicYear: '',
    statusText: '',
    badgeText: '',
    announcement: '',
    contactPerson: '',
    brochureUrl: '',
  },
  embeds: {
    youtubeTitle: '',
    youtubeSubtitle: '',
    youtubeUrl: '',
    mapTitle: 'Lokasi SMP Negeri 1 Bengkalis',
    mapIframeUrl:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.723145028092!2d102.1114250749658!3d1.4735999985122176!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31d15fc2a5b8205f%3A0x296dbf2b26c6d2dc!2sSMP%20Negeri%201%20Bengkalis!5e0!3m2!1sid!2sid!4v1710000000000!5m2!1sid!2sid',
  },
  facilities: [],
  extracurriculars: [],
  agendas: [],
  footer: {
    aboutText: '',
    address: '',
    phone: '',
    whatsapp: '',
    email: '',
    openingHours: '',
    socialLinks: {
      instagram: '',
      youtube: '',
      facebook: '',
      twitter: '',
    },
    copyright: '',
  },
  themeConfig: DEFAULT_THEME_CONFIG,
  newsCategories: ['Prestasi', 'Pengumuman', 'Kegiatan', 'Akademik', 'Ekstrakurikuler', 'Alumni'],
  googleAppsScript: {
    enabled: true,
    webAppUrl: DEFAULT_APPS_SCRIPT_WEB_APP_URL || '',
    folderId: DEFAULT_APPS_SCRIPT_FOLDER_ID || '',
    spreadsheetId: '',
    autoCreateFolder: true,
    testStatus: 'untested',
  },
  visi: "Terwujudnya insan yang berakhlak mulia, cerdas, berprestasi, kreatif, mandiri, dan berwawasan lingkungan.",
  misi: "Menanamkan nilai-nilai keimanan dan ketakwaan melalui pembiasaan kegiatan keagamaan di sekolah.\nMenyelenggarakan pembelajaran yang aktif, inovatif, kreatif, efektif, dan menyenangkan.\nMengembangkan potensi akademik dan non-akademik secara optimal sesuai bakat dan minat peserta didik.\nMembina kemandirian, kedisiplinan, dan budi pekerti luhur dalam kehidupan sehari-hari.\nMewujudkan lingkungan sekolah yang bersih, sehat, rindang, asri, dan peduli terhadap pelestarian alam.",
  visiMisiTitle: "Visi & Misi Instansi",
  visiMisiSubtitle: "Arah pandang dan komitmen dedikasi dalam mewujudkan generasi penerus yang unggul dan berkarakter.",
  gtkList: [],
  gtkSectionTitle: "Guru & Tenaga Kependidikan",
  gtkSectionSubtitle: "Mengenal para pendidik dan tenaga kependidikan berdedikasi yang membimbing dan menginspirasi generasi penerus bangsa.",
};

// Empty default articles: all articles are loaded purely from Firebase and cache
export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [];

